spring:
  config:
    import:
      - classpath:dev/health-check.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Example for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: nanhe
    password: nanhe